### ISSUE TITLE
vscode  调试next.conifg.js 配置

### ISSUE THREAD

**Issue by changfu2015** [Microsoft/vscode-recipes#130] opened 2018-09-14 03:55 UTC
断电没有拦截到，打印是看到有执行
![image](https://user-images.githubusercontent.com/14310202/45528884-0014fe80-b815-11e8-94ea-19fca91b243b.png)

**Comment by auchenberg** [comment] 2019-02-04 22:34
Possibly duplicate of https://github.com/Microsoft/vscode-recipes/issues/80

**Closed by auchenberg** 2019-02-04 22:34 UTC
