### ISSUE TITLE
Next.js example does not seem to work with next@^6.0.0.0

### ISSUE THREAD

**Issue by nico29** [Microsoft/vscode-recipes#103] opened 2018-05-17 08:15 UTC
Hello,

I'm trying to debug Next.js applications, running with the latest version of [next.js](https://github.com/zeit/next.js) which is 6.0.3. But I did not manage to have my breakpoints recognized in the vscode node debugger.

To reproduce, you can clone [nextgram](https://github.com/now-examples/nextgram) and update next (also react and react-dom) to the latest version.

Here is my launch configuration. I changed the `runtimeExecutable` to use the local next installation:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Next: Chrome",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceFolder}"
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Next: Node",
            "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/next",
            "runtimeArgs": [
                "--inspect"
            ],
            "port": 9229,
            "console": "integratedTerminal"
        }
    ],
    "compounds": [
        {
            "name": "Next: Full",
            "configurations": ["Next: Node", "Next: Chrome"]
        }
    ]
}
```

All my breakpoint are `Unverified breakpoint, Breakpoints set but not yet bound` so I assume this could be a source map issue.

I'm running **MacOS 10.13.3** with **Node v10.1.0** and **npm 6.0.1**.
Did someone experience a similar issue ❓
Thank you 😸

**Comment by timjbray** [comment] 2018-05-26 05:47
Hello, 
I have the same issue - same platform (MacOS) & latest Node, npm
`Unverified breakpoint, Breakpoint ignored because generated code not found (source map problem?)`
Thanks!

**Comment by frol** [comment] 2018-05-26 09:40
The same issue here:

OS: Arch Linux, x64 \
VS Code 1.23.1 \
Node.js 10.2.1 \
Next.js 6.0.3 \
React 16.4.0

**Comment by jamesgibson14** [comment] 2018-06-07 15:17
Same launch.json:
MacOS
node: 8.11.1
"next": "^6.0.3",
    "react": "^16.4.0",
    "react-dom": "^16.4.0"

**Comment by timmywil** [comment] 2018-06-07 19:07
I was able to fix the issue for myself. I was staring at the source map for a while and noticed that the `./` was missing from the paths that didn't include `node_modules` (e.g. `"webpack:///actions/index.js"` instead of `"webpack:///./actions/index.js"`). I tried the following and it worked:

```
...
      "sourceMapPathOverrides": {
        ...
        "webpack:///*": "${webRoot}/*"
      },
...
```

I don't know if this is the proper fix. Maybe there is an issue in babel, next.js, webpack, or vs code, but this got breakpoints working again.

**Comment by leifdalan** [comment] 2018-06-07 23:42
@timmywil I build from the `/src` folder. From your solution, where would I append `/src`? I've tried a few things:

```
{
            "type": "chrome",
            "request": "launch",
            "name": "Next: Chrome",
            "url": "http://localhost:8000",
            "webRoot": "${workspaceFolder}/src",
            "sourceMapPathOverrides": {
                "webpack:///*": "${webRoot}/src/*"
            },

        },
```
and every permutation of adding/removing `/src` to webRoot and the webpack `sourceMapPathOverrides`. Any help/advice would be greatly appreciated! I miss my breakpoints.

**Comment by auchenberg** [comment] 2018-06-08 18:39
Issue seems to be related to a change in next.js. I've opened an issue on their side: https://github.com/zeit/next.js/issues/4571

**Comment by leifdalan** [comment] 2018-06-11 15:36
@timmywil's fix worked for me. Thanks!

**Comment by nico29** [comment] 2018-06-12 07:04
@timmywil Thank, w/ your solution Chrome debugging worked. Still no luck for server side code, like `getInitialProps`. Thank @auchenberg for opening an issue on Next side.

**Comment by lipp** [comment] 2018-10-25 12:56
Trying the debug config for next.js 7. Still not working for Chrome. Breaking at random source lines. @zerocity config is not working for me. 

Debugging in Chrome dev tools is working -> not sure it is a Next.js issue.

**Comment by justinphilpott** [comment] 2018-11-08 23:42
I have the same issue, unpredictable code breaking, rather depressing! 
@zerocity not working for me.

**Comment by zerocity** [comment] 2018-11-09 16:40
I tested the config on windows with next 7 and it works.
I changed only
     "console": "integratedTerminal" ->
     "console": "internalConsole"
i had some issues with WSL. 
here is example repo https://github.com/zerocity/vscode-next-debugger-test

**Comment by shamoorti** [comment] 2018-12-06 15:42
Got the same issue, I tried everything and still does not work! It just randomly jumps over some line and breaks in some line that it doesn't have any breakpoints!

**Comment by zerocity** [comment] 2018-12-07 13:42
Hi,

This is an example repo which was working for me

https://github.com/zerocity/vscode-next-debugger-test

Maybe this helps

shamoorti <notifications@github.com> schrieb am Do., 6. Dez. 2018, 16:42:

**Comment by auchenberg** [comment] 2019-02-04 22:32
Duplicate of https://github.com/Microsoft/vscode-recipes/issues/80

**Closed by auchenberg** 2019-02-04 22:32 UTC
