### ISSUE TITLE
Meteor:Node launch config never starts listening / 

### ISSUE THREAD

**Issue by ChuckIrvine** [Microsoft/vscode-recipes#58] opened 2018-01-11 21:19 UTC
I was able to get everything working with the simple todo project. However, when I tried to update my actual web app project, I get the error:

`Cannot connect to runtime process, timeout after 60000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9229).`

Nothing is running already on port 9229. I get the same error with higher timeout settings.

In the debug console, all that shows is:

`Debugging with inspector protocol because a runtime executable is set.
/usr/local/bin/npm run debug`

Any ideas on how I can debug?

**Comment by arlohosk** [comment] 2018-01-26 18:58
I am having the same issue - have tried increasing timeout limit, and have tried ports 5858 and 5959 in addition. 
In my debug console, all that shows up is:
`Debugging with inspector protocol because a runtime executable is set.
C:\Program Files (x86)\nodejs\npm.cmd run debug 
npm WARN lifecycle The node binary used for scripts is C:\Program Files\nodejs\node.exe but npm is using C:\Program Files (x86)\nodejs\node.exe itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.`

**Comment by auchenberg** [comment] 2018-01-26 21:26
Which version of meteor are you using? You need to use v1.6 or newer as outlined here https://github.com/Microsoft/vscode-recipes/tree/master/meteor @ChuckIrvine @arlohosk

**Comment by arlohosk** [comment] 2018-01-26 21:28
Yes, using meteor 1.6.0.1 . Checked node and npm in the project as well, they are at 8.9+ and 5.5+

**Comment by auchenberg** [comment] 2018-01-26 22:21
@arlohosk Can you try running `meteor run --inspect in your terminal and paste the output in here?

**Comment by arlohosk** [comment] 2018-01-27 07:07
Sure - to be clear i'm using a settings file that is required for startup:
`meteor run --inspect --settings ../pathtosettings/settingslocal.json`

(1) Here is the output - it seems to run fine, but it does not stop at debug points that i set. I can see the nodejs process in chrome://inspect and brows to the console, though I'm not sure the files is available to set breakpoints on like in frontend devtools
```
W20180127-01:42:15.258(-5)? (STDERR) Debugger listening on ws://127.0.0.1:9229/a76a81db-d71b-4257-9143-7556dfe5110e
W20180127-01:42:16.096(-5)? (STDERR) For help see https://nodejs.org/en/docs/inspector
```

(2) In my package.json, instead of the simply having `meteor run` or `meteor run --inspect` for the `start` and `debug` properties, I am adding the settings file path. I'm not sure if the path is relative to the npm executable, or the project root (i.e. the folder in which .meteor and .vscode is located. This is what I am assuming)

**Comment by auchenberg** [comment] 2018-01-27 23:40
@arlohosk Can I get you to open an new issue with details about your setup (Node + meteor version, file structure and your launch.json), as it sounds you might have a sourcemapping issue, and not problems by having our debuggger connecting to Meteor.

We don't wanna re-use issues that aren't the same.

**Comment by arlohosk** [comment] 2018-01-28 18:25
sure will do so now

**Comment by auchenberg** [comment] 2018-02-02 20:02
Closing as this most likely is caused by using an old meteor version. Will reopen if not.

**Closed by auchenberg** 2018-02-02 20:02 UTC

**Comment by ChuckIrvine** [comment] 2018-02-21 14:59
It turns out that my problem was a typo in the name of my dev settings file in my package.json file. The error was only apparent when I turned on logging as instructed in https://github.com/Microsoft/vscode-recipes/issues/70.
