### ISSUE TITLE
Error on Windows?

### ISSUE THREAD

**Issue by riker09** [Microsoft/vscode-recipes#17] opened 2017-08-09 07:31 UTC
I'm trying to get remote debugging in a docker container to work. I have a strong linux background but at work I'm stuck with Windows (unfortunately). I think this error has to do something with Windows, but I'm not 100% sure:

```
PS C:\Users\MYUSER\projects\vscode-recipes\Docker-TypeScript> cd 'c:\Users\MYUSER\projects\vscode-recipes\Docker-TypeScript'; 'C:\Program Files\nodejs\npm.cmd' run docker-debug
In Zeile:1 Zeichen:99
+ ... pes\Docker-TypeScript'; 'C:\Program Files\nodejs\npm.cmd' run docker- ...
+                                                               ~~~
Unerwartetes Token "run" in Ausdruck oder Anweisung.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken

PS C:\Users\MYUSER\projects\vscode-recipes\Docker-TypeScript>
```

**Comment by auchenberg** [comment] 2017-08-10 02:02
@riker09 Can you try to post your "launch.json" file in here? Looks like `npm.cmd` is being called in a wrong way.

**Comment by riker09** [comment] 2017-08-10 07:29
Sure, no problem:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch in Docker",
      "protocol": "legacy",
      "runtimeExecutable": "npm",
      "runtimeArgs": [ "run", "docker-debug" ],
      "port": 5858,
      "restart": true,
      "timeout": 60000,
      "localRoot": "${workspaceRoot}",
      "remoteRoot": "/app",
      "outFiles": [
        "${workspaceRoot}/**/*.js"
      ],
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen"
    }
  ]
}
```

As a workaround I switched `console` to `externalTerminal`, that seem to work just fine, albeit an extra window is somwhat annoying. 😐

**Comment by auchenberg** [comment] 2017-08-10 17:15
@riker09 What version of Code are you using?

**Comment by roblourens** [comment] 2017-08-10 18:51
```
PS C:\Users\roblou\code\jstest> 'C:\Program Files\nodejs\npm.cmd' run build
At line:1 char:35
+ 'C:\Program Files\nodejs\npm.cmd' run build
+                                   ~~~
Unexpected token 'run' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
```

I guess that isn't valid PS syntax... I actually am not sure what it should be...?

**Comment by roblourens** [comment] 2017-08-10 18:52
Oh, it should be `& 'C:\Program Files\nodejs\npm.cmd' run build`, otherwise the `program files/...` arg is just a string.

**Comment by riker09** [comment] 2017-08-11 08:51
@auchenberg I was using VS Code 1.14.

**Comment by auchenberg** [comment] 2017-08-11 18:04
@riker09 Gotcha. And you are using PowerShell as your default shell? Seems like you have hit a scenario that we don't support today for the `integratedTerminal`, as we are running the launch script for non-PS.

**Comment by riker09** [comment] 2017-08-15 07:40
I haven't touched the defaults made by Windows, so I guess my default shell is powershell. I would confirm it, but I don't know where to start looking.

**Comment by auchenberg** [comment] 2017-08-15 18:20
This issue was moved to Microsoft/vscode-node-debug2#133

**Comment by auchenberg** [comment] 2017-08-15 18:21
I've moved to the issue to https://github.com/Microsoft/vscode-node-debug2/issues/133, which is our repo for our node debugger.

@weinand Can you close this issue, thanks!

**Comment by weinand** [comment] 2017-08-15 19:20
I'm not sure that the issue is node2 related: the launch config is using the "legacy" protocol and the terminal handling is done in VS Code anyway.

**Comment by auchenberg** [comment] 2017-10-31 20:53
@weinand Can we close this as we are tracking in Microsoft/vscode-node-debug2#133, ?

**Closed** 2017-11-27 20:57 UTC
