### ISSUE TITLE
console.log() not printing to terminal when debugging Electron apps.

### ISSUE THREAD

**Issue by Borkason** [Microsoft/vscode-recipes#49] opened 2017-12-21 22:54 UTC
I followed https://github.com/Microsoft/vscode-recipes/tree/master/Electron to configure debugging for Electron apps. I added a simple `console.log("Hello World");` at the end of main.js. What did I do wrong?

![grafik](https://user-images.githubusercontent.com/2971735/34278305-3786c64c-e6aa-11e7-9041-444e500469c0.png)

**Comment by auchenberg** [comment] 2017-12-24 05:00
@Borkason This is probably caused by script execution being continued, so VS Code attaches to your Electron Main process after your `console.log` has been executed.

What if you set your log in later code, or delay it by 200ms?

@roblourens It looks like the `debug-brk` flag is used for Electron Main processes when `inspect-brk` should be used. https://github.com/Microsoft/vscode-node-debug2/blob/fe51af537b02e178a0c0c537dcafc9f565a22d0e/src/nodeDebugAdapter.ts#L843

**Comment by roblourens** [comment] 2017-12-24 15:19
That shouldn't matter, can you set `"trace": true` in your launch config, run it again, and attach the log here?

**Comment by SteelPhase** [comment] 2017-12-28 22:24
@Borkason can you try setting `"outputCapture": "std"` in your launch.json

should look close to this
```json
{
      "version": "0.2.0",
      "configurations": [
          {
              "type": "node",
              "request": "launch",
              "name": "Electron: Main",
              "protocol": "inspector",
              "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
              "runtimeArgs": [
                  "--remote-debugging-port=9223",
                  "."
              ],
              "windows": {
                  "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd"
              },
              "outputCapture": "std"
          },
          {
              "name": "Electron: Renderer",
              "type": "chrome",
              "request": "attach",
              "port": 9223,
              "webRoot": "${workspaceRoot}",
              "timeout": 30000
          }
      ],
      "compounds": [
          {
              "name": "Electron: All",
              "configurations": [
                  "Electron: Main",
                  "Electron: Renderer"
              ]
          }
      ]
  }
```

**Comment by auchenberg** [comment] 2018-02-02 20:00
Closing due to in activity.

**Closed by auchenberg** 2018-02-02 20:00 UTC
